baseurl = "https://people.umass.edu/jboke/"
title = "Jimi B Oke"
languageCode = "en-us"
canonifyurls = true
relativeurls = false
paginate = 10
theme = "robjhyndman"
DisqusShortname = "researchtips"
#googleAnalytics = "UA-5004894-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
pluralizeListTitles = false
buildFuture = true

[markup.goldmark.renderer]
unsafe= true

[params]

# Date format (refer to Go's date format: http://flippinggodateformat.com)
date_format = "January 2 2006"

# Number of posts to show on main page.
posts_count = 3

# Number of publications to show on main page.
pubs_count = 5

# Number of seminars to show on main page.
seminars_count = 5

# options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"

[[params.social]]
  icon = "university"
  icon_pack = "fa"
  link = "http://cee.umass.edu/"
  text = "Department of Civil and Environmental Engineering, University of Massachusetts, Amherst, MA 01003."

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:jboke@umass.edu"
  text = "jboke@umass.edu"

[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "https://twitter.com/jimioke"
  text = "@jimioke"
  site = "Twitter"

[[params.social]]
  icon = "github-alt"
  icon_pack = "fa"
  link = "https://github.com/jimioke/"
  text = "jimioke"
  site = "GitHub"

[[params.social]]
  icon = "google-scholar"
  icon_pack = "ai"
  link = "https://scholar.google.com/citations?user=R6I47vYAAAAJ&hl=en"
  text = "Google Scholar"

[[params.social]]
  icon = "linkedin"
  icon_pack = "fa"
  link = "https://www.linkedin.com/in/jimi-oke-20768b23/"
  text = "Linkedin"
  site = "Linkedin"


# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 2

[[menu.main]]
  name = "Presentations"
  url = "/presentations/"
  weight = 3

[[menu.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 4

[[menu.main]]
  name = "Datasets and Software"
  url = "/datacode/"
  weight = 5

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 6

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 7
